# Here are a load of searches that can be performed through the API.
Search::FindPlateByBarcode.create!(:name => 'Find plates by barcode')
Search::FindTubeByBarcode.create!(:name => 'Find tubes by barcode')
Search::FindModelByName.create!(:name => 'Find project by name', :model_name => 'Project')
Search::FindModelByName.create!(:name => 'Find study by name',   :model_name => 'Study')
Search::FindModelByName.create!(:name => 'Find sample by name',  :model_name => 'Sample')
Search::FindSourcePlatesByDestinationPlateBarcode.create!(:name => 'Find source plates by destination plate barcode')
Search::FindSourceTubesByDestinationTubeBarcode.create!(:name => 'Find source tubes by destination tube barcode')
Search::FindUserByLogin.create!(:name => 'Find user by login')
Search::FindUserBySwipecardCode.create!(:name => 'Find user by swipecard code')
Search::FindPulldownPlates.create!(:name => 'Find pulldown plates')
