---
Sanger_168tags - 10 mer tags:
  adapter_type_name: Sanger 168
  visible: true
  tags:
    1: ATCACGTT
    2: CGATGTTT
    3: TTAGGCAT
    4: TGACCACT
    5: ACAGTGGT
    6: GCCAATGT
    7: CAGATCTG
    8: ACTTGATG
    9: GATCAGCG
    10: TAGCTTGT
    11: GGCTACAG
    12: CTTGTACT
    13: TGGTTGTT
    14: TCTCGGTT
    15: TAAGCGTT
    16: TCCGTCTT
    17: TGTACCTT
    18: TTCTGTGT
    19: TCTGCTGT
    20: TTGGAGGT
    21: TCGAGCGT
    22: TGATACGT
    23: TGCATAGT
    24: TTGACTCT
    25: TGCGATCT
    26: TTCCTGCT
    27: TAGTGACT
    28: TACAGGAT
    29: TCCTCAAT
    30: TGTGGTTG
    31: TAGTCTTG
    32: TTCCATTG
    33: TCGAAGTG
    34: TAACGCTG
    35: TTGGTATG
    36: TGAACTGG
    37: TACTTCGG
    38: TCTCACGG
    39: TCAGGAGG
    40: TAAGTTCG
    41: TCCAGTCG
    42: TGTATGCG
    43: TCATTGAG
    44: TGGCTCAG
    45: TATGCCAG
    46: TCAGATTC
    47: TACTAGTC
    48: TTCAGCTC
    49: TGTCTATC
    50: TATGTGGC
    51: TTACTCGC
    52: TCGTTAGC
    53: TACCGAGC
    54: TGTTCTCC
    55: TTCGCACC
    56: TTGCGTAC
    57: TCTACGAC
    58: TGACAGAC
    59: TAGAACAC
    60: TCATCCTA
    61: TGCTGATA
    62: TAGACGGA
    63: TGTGAAGA
    64: TCTCTTCA
    65: TTGTTCCA
    66: TGAAGCCA
    67: TACCACCA
    68: TGCGTGAA
    69: GGTGAGTT
    70: GATCTCTT
    71: GTGTCCTT
    72: GACGGATT
    73: GCAACATT
    74: GGTCGTGT
    75: GAATCTGT
    76: GTACATCT
    77: GAGGTGCT
    78: GCATGGCT
    79: GTTAGCCT
    80: GTCGCTAT
    81: GGAATGAT
    82: GAGCCAAT
    83: GCTCCTTG
    84: GTAAGGTG
    85: GAGGATGG
    86: GTTGTCGG
    87: GGATTAGG
    88: GATAGAGG
    89: GTGTGTCG
    90: GCAATCCG
    91: GACCTTAG
    92: GCCTGTTC
    93: GCACTGTC
    94: GCTAACTC
    95: GATTCATC
    96: GTCTTGGC
    97: GTAGAAGC
    98: GATGGTCC
    99: GTGCTACC
    100: GCGATTAC
    101: GGTTGGAC
    102: GGCACAAC
    103: GACACTTA
    104: GTGCAGTA
    105: GGAGTCTA
    106: GCTATGGA
    107: GAGTGCGA
    108: GTAACCGA
    109: GGCAAGCA
    110: GCCTTACA
    111: GAACGACA
    112: GCAGGTAA
    113: GCGTCGAA
    114: CGTTCGGT
    115: CACCAGGT
    116: CTGCGAGT
    117: CCGTATCT
    118: CGCTTCCT
    119: CAAGACCT
    120: CACACACT
    121: CCTAGTAT
    122: CCACCGAT
    123: CTTCACAT
    124: CTATCATG
    125: CATGAATG
    126: CCACTTGG
    127: CTGTACGG
    128: CTAGATAG
    129: CACTCGAG
    130: CCGACAAG
    131: CTTGCTTC
    132: CATAGGTC
    133: CACATTGC
    134: CGCTAAGC
    135: CAACCTCC
    136: CAGCTGAC
    137: CTCAAGAC
    138: CGTGTCAC
    139: CCATGCAC
    140: CGTTACTA
    141: CAAGTAGA
    142: CTCTCTCA
    143: CGACTGCA
    144: CCTGAGCA
    145: CAGGCTAA
    146: CGGAGGAA
    147: AGGAGATT
    148: AGGCAGCT
    149: ACGTTCAT
    150: AACGTGTG
    151: AGACCGTG
    152: ACCTCTGG
    153: ATCCTAGG
    154: ATCAACCG
    155: AGGTCACG
    156: ACTGTTAG
    157: AAGAGTAG
    158: ATTCGGAG
    159: ACGCAATC
    160: ACAAGTGC
    161: ATGGATCC
    162: AGAGGACC
    163: ATCTCCAC
    164: ATTGGCTA
    165: AATCCTGA
    166: AGGATTCA
    167: AACTGGCA
    168: ACAACGCAAT
NEXTflex-96 barcoded adapters:
  adapter_type_name: TruSeq PCR Free
  visible: true
  tags:
    1: AACGTGAT
    2: AAACATCG
    3: ATGCCTAA
    4: AGTGGTCA
    5: ACCACTGT
    6: ACATTGGC
    7: CAGATCTG
    8: CATCAAGT
    9: CGCTGATC
    10: ACAAGCTA
    11: CTGTAGCC
    12: AGTACAAG
    13: AACAACCA
    14: AACCGAGA
    15: AACGCTTA
    16: AAGACGGA
    17: AAGGTACA
    18: ACACAGAA
    19: ACAGCAGA
    20: ACCTCCAA
    21: ACGCTCGA
    22: ACGTATCA
    23: ACTATGCA
    24: AGAGTCAA
    25: AGATCGCA
    26: AGCAGGAA
    27: AGTCACTA
    28: ATCCTGTA
    29: ATTGAGGA
    30: CAACCACA
    31: GACTAGTA
    32: CAATGGAA
    33: CACTTCGA
    34: CAGCGTTA
    35: CATACCAA
    36: CCAGTTCA
    37: CCGAAGTA
    38: CCGTGAGA
    39: CCTCCTGA
    40: CGAACTTA
    41: CGACTGGA
    42: CGCATACA
    43: CTCAATGA
    44: CTGAGCCA
    45: CTGGCATA
    46: GAATCTGA
    47: CAAGACTA
    48: GAGCTGAA
    49: GATAGACA
    50: GCCACATA
    51: GCGAGTAA
    52: GCTAACGA
    53: GCTCGGTA
    54: GGAGAACA
    55: GGTGCGAA
    56: GTACGCAA
    57: GTCGTAGA
    58: GTCTGTCA
    59: GTGTTCTA
    60: TAGGATGA
    61: TATCAGCA
    62: TCCGTCTA
    63: TCTTCACA
    64: TGAAGAGA
    65: TGGAACAA
    66: TGGCTTCA
    67: TGGTGGTA
    68: TTCACGCA
    69: AACTCACC
    70: AAGAGATC
    71: AAGGACAC
    72: AATCCGTC
    73: AATGTTGC
    74: ACACGACC
    75: ACAGATTC
    76: AGATGTAC
    77: AGCACCTC
    78: AGCCATGC
    79: AGGCTAAC
    80: ATAGCGAC
    81: ATCATTCC
    82: ATTGGCTC
    83: CAAGGAGC
    84: CACCTTAC
    85: CCATCCTC
    86: CCGACAAC
    87: CCTAATCC
    88: CCTCTATC
    89: CGACACAC
    90: CGGATTGC
    91: CTAAGGTC
    92: GAACAGGC
    93: GACAGTGC
    94: GAGTTAGC
    95: GATGAATC
    96: GCCAAGAC
